In [14]:
#Import the necessary data manipulation and visualization libraries

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

In [15]:
#Import the machine learning algorithms from sklearn

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans

In [16]:
#Import some utility and metric classes

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import KFold, cross_val_score

In [17]:
#Defining the header since the data does not have any defined and importing the dataset

headers = ["A1","A2","A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15","A16"]

df = pd.read_csv("data/data.csv", header=None, names=headers, na_values='?')

In [18]:
#Explore the data.

df.shape

(690, 16)

In [19]:
#Explore the field types.

df.dtypes

A1      object
A2     float64
A3     float64
A4      object
A5      object
A6      object
A7      object
A8     float64
A9      object
A10     object
A11      int64
A12     object
A13     object
A14    float64
A15      int64
A16     object
dtype: object

In [20]:
#View the format of the data.

df.head()

A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202.0    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43.0  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280.0  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100.0    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120.0    0   +

In [21]:
#Checking how many null values are in each column.

df.isnull().sum()

A1     12
A2     12
A3      0
A4      6
A5      6
A6      9
A7      9
A8      0
A9      0
A10     0
A11     0
A12     0
A13     0
A14    13
A15     0
A16     0
dtype: int64

In [22]:
#Unique function is used to identify the unique values in the 'A1' field.

df.A1.unique()

array(['b', 'a', nan], dtype=object)

In [23]:
#View the number of records for each attribute

df.groupby(['A1'])\
  .size()\
  .sort_values(ascending=False)  

A1
b    468
a    210
dtype: int64

In [24]:
df_data = df.fillna({"A1": "b"})

In [25]:
df_data.A1.unique()

array(['b', 'a'], dtype=object)

In [26]:
df_data.mean()

A2       31.568171
A3        4.758725
A8        2.223406
A11       2.400000
A14     184.014771
A15    1017.385507
dtype: float64

In [27]:
df2 = df_data.fillna(df_data.mean())
df2.head()

A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202.0    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43.0  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280.0  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100.0    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120.0    0   +

In [28]:
categorical = df2.dtypes[df2.dtypes == "object"].index
categorical

Index([u'A1', u'A4', u'A5', u'A6', u'A7', u'A9', u'A10', u'A12', u'A13',
       u'A16'],
      dtype='object')

In [29]:
for c in categorical:
    df2[c] = df2[c].astype('category')
    df2[c] = df2[c].cat.codes
df2.head()

A1     A2     A3  A4  A5  A6  A7    A8  A9  A10  A11  A12  A13    A14  A15  \
0   1  30.83  0.000   1   0  12   7  1.25   1    1    1    0    0  202.0    0   
1   0  58.67  4.460   1   0  10   3  3.04   1    1    6    0    0   43.0  560   
2   0  24.50  0.500   1   0  10   3  1.50   1    0    0    0    0  280.0  824   
3   1  27.83  1.540   1   0  12   7  3.75   1    1    5    1    0  100.0    3   
4   1  20.17  5.625   1   0  12   7  1.71   1    0    0    0    2  120.0    0   

   A16  
0    0  
1    0  
2    0  
3    0  
4    0

In [30]:
df2.dtypes

A1        int8
A2     float64
A3     float64
A4        int8
A5        int8
A6        int8
A7        int8
A8     float64
A9        int8
A10       int8
A11      int64
A12       int8
A13       int8
A14    float64
A15      int64
A16       int8
dtype: object

In [31]:
train, test = train_test_split(df2, test_size=0.2, train_size=0.8)
test.head()

A1     A2      A3  A4  A5  A6  A7      A8  A9  A10  A11  A12  A13    A14  \
414   1  22.25   0.460   1   0   8   7   0.125   0    0    0    1    0  280.0   
203   0  20.75  10.250   1   0  10   7   0.710   1    1    2    1    0   49.0   
648   1  25.58   0.335   1   0   8   3   3.500   0    0    0    1    0  340.0   
73    1  44.25   0.500   1   0   9   7  10.750   1    0    0    0    2  400.0   
584   0  28.08  15.000   2   2   4   8   0.000   1    0    0    0    0    0.0   

       A15  A16  
414     55    1  
203      0    0  
648      0    1  
73       0    1  
584  13212    0

In [32]:
X_train = train.drop("A16", axis=1)
Y_train = train["A16"]
X_test = test.drop("A16", axis=1)
Y_test = test["A16"]
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((552, 15), (552,), (138, 15), (138,))

In [33]:
scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)

pca = PCA(0.95)

pca.fit(X_train)

pca.n_components_

X_train = pca.transform(X_train)

X_train = pd.DataFrame(X_train)

In [34]:
scaler = StandardScaler()

scaler.fit(X_test)

X_test = scaler.transform(X_test)

pca = PCA(0.95)

pca.fit(X_test)

pca.n_components_

X_test = pca.transform(X_test)

X_test = pd.DataFrame(X_test)

In [35]:
#Viewing the data the standardisation of the data can be seen

X_test.head()

0         1         2         3         4         5         6   \
0 -1.369841 -0.861229 -0.745065 -0.915329 -0.905585 -0.678369 -0.304663   
1  1.314403 -0.977220 -1.553244  0.368666 -0.143509 -0.339936 -1.136929   
2 -1.010199 -0.701359  0.053610 -1.413541 -0.923869  0.330286 -0.642772   
3  0.212056 -0.678264  1.837907 -2.377953  0.205893 -0.643041  3.235865   
4  0.784107  3.050485 -2.123199  4.871819 -0.152050  0.304236  3.952932   

         7         8         9         10        11        12  
0 -0.172623  0.075799  0.812853  0.106463  0.708047  0.275672  
1  0.234565 -1.441561 -0.513334  1.160439 -0.219484 -0.155663  
2  0.179055  0.334492  0.561356 -0.555699  1.050522 -0.277807  
3 -0.245895 -0.942605 -1.208856 -0.258224 -0.359033 -0.437860  
4  4.573479 -0.145574  0.799699  0.762741  1.371913 -0.190324

In [36]:
# Applying Logistics Regression to the Standardised Data

logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
acc_log = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_log

78.99

In [37]:
# Support Vector Machines

svc = SVC()
svc.fit(X_train, Y_train)
Y_pred = svc.predict(X_test)
acc_svc = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_svc

76.09

In [38]:
# KNN Classification method applied

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, Y_train)
Y_pred = knn.predict(X_test)
acc_knn = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_knn

81.88

In [39]:
# Gaussian Naive Bayes

gaussian = GaussianNB()
gaussian.fit(X_train, Y_train)
Y_pred = gaussian.predict(X_test)
acc_gaussian = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_gaussian

77.54

In [40]:
# Perceptron

perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
Y_pred = perceptron.predict(X_test)
acc_perceptron = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_perceptron

/Library/Python/2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


79.71

In [41]:
# Linear SVC

linear_svc = LinearSVC()
linear_svc.fit(X_train, Y_train)
Y_pred = linear_svc.predict(X_test)
acc_linear_svc = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_linear_svc

78.99

In [42]:
# Stochastic Gradient Descent

sgd = SGDClassifier()
sgd.fit(X_train, Y_train)
Y_pred = sgd.predict(X_test)
acc_sgd = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_sgd

/Library/Python/2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


75.36

In [43]:
# Decision Tree

decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, Y_train)
Y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_decision_tree

69.57

In [44]:
# Random Forest

random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, Y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_train, Y_train)
acc_random_forest = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_random_forest

81.16

In [45]:
#Comparison of the various classification methods.

models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree]})
models.sort_values(by='Score', ascending=False)

Model  Score
1                         KNN  81.88
3               Random Forest  81.16
5                  Perceptron  79.71
2         Logistic Regression  78.99
7                  Linear SVC  78.99
4                 Naive Bayes  77.54
0     Support Vector Machines  76.09
6  Stochastic Gradient Decent  75.36
8               Decision Tree  69.57

In [46]:
#Applying Random Forest Classifier to the data.

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

X_train, Y_train = make_classification(n_samples=138, n_features=13, 
                                     n_informative=2, n_redundant=2,
                                     random_state=None, shuffle=True)

clf = RandomForestClassifier(max_depth=None, random_state=None)

clf.fit(X_train, Y_train)
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini', 
           max_depth=None ,max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

print(clf.feature_importances_)

print(clf.predict(X_test))

[0.02161765 0.02886613 0.09117107 0.30433106 0.0225107  0.00569456
 0.00737058 0.01613667 0.02701382 0.0372054  0.0501533  0.01962226
 0.36830679]
[0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 1 0
 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 0 0 1
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]


In [47]:
Y_pred = clf.predict(X_test)
acc_log = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_log

42.03

In [48]:
#Performing Recall on the Reclassified data

from sklearn.metrics import recall_score

y_true = Y_train
y_pred = clf.predict(X_test)
recall_score(y_true, y_pred, average=None)

array([0.72463768, 0.27536232])

In [49]:
acc_log = round(recall_score(y_true,y_pred) * 100, 2)
acc_log

27.54

In [50]:
#Performing Randomised Search on the data to determine 
#the best parameters for the RandomForest Classifier

print(__doc__)

import numpy as np

from time import time
from scipy.stats import randint as sp_randint

from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

# build a classifier
clf = RandomForestClassifier(n_estimators=10)


# Utility function to report best scores
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")


# specify parameters and distributions to sample from
param_dist = {"n_estimators": sp_randint(1, 20),
              "max_depth": [3, None],
              "max_features": sp_randint(1, 11),
              "min_samples_split": sp_randint(2, 11),
              "min_samples_leaf": sp_randint(1, 11),
              "bootstrap": [True, False]}

# run randomized search
n_iter_search = 20
random_search = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=n_iter_search)

start = time()
random_search.fit(X_train, Y_train)
print("RandomizedSearchCV took %.2f seconds for %d candidates"
      " parameter settings." % ((time() - start), n_iter_search))
report(random_search.cv_results_)

Automatically created module for IPython interactive environment
RandomizedSearchCV took 1.63 seconds for 20 candidates parameter settings.
Model with rank: 1
Mean validation score: 0.957 (std: 0.031)
Parameters: {'bootstrap': False, 'min_samples_leaf': 3, 'n_estimators': 11, 'min_samples_split': 9, 'max_features': 4, 'max_depth': 3}

Model with rank: 2
Mean validation score: 0.949 (std: 0.041)
Parameters: {'bootstrap': True, 'min_samples_leaf': 9, 'n_estimators': 8, 'min_samples_split': 7, 'max_features': 7, 'max_depth': 3}

Model with rank: 2
Mean validation score: 0.949 (std: 0.041)
Parameters: {'bootstrap': False, 'min_samples_leaf': 8, 'n_estimators': 7, 'min_samples_split': 3, 'max_features': 9, 'max_depth': 3}

Model with rank: 2
Mean validation score: 0.949 (std: 0.041)
Parameters: {'bootstrap': True, 'min_samples_leaf': 10, 'n_estimators': 10, 'min_samples_split': 8, 'max_features': 8, 'max_depth': 3}

Model with rank: 2
Mean validation score: 0.949 (std: 0.027)
Parameters: {'

In [51]:
#The best parameters from the Randomised Search applied to Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

X_train, Y_train = make_classification(n_samples=138 ,n_features=13, 
                                     n_informative=2, n_redundant=2,
                                     random_state=None, shuffle=True)

clf = RandomForestClassifier(max_depth=None, random_state=None)

clf.fit(X_train, Y_train)
RandomForestClassifier(bootstrap=False, max_depth=3 ,max_features=8, 
           min_samples_leaf=5, min_samples_split=3,n_estimators=15)

print(clf.feature_importances_)

print(clf.predict(X_test))

[0.01458884 0.01613193 0.02108012 0.00987535 0.0142051  0.0228721
 0.13769682 0.04949433 0.27296472 0.00891309 0.00835857 0.00424031
 0.41957871]
[1 0 0 0 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 0 0 1 0 0 1
 0 1 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 0
 0 0 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 1 1 1 0 0 1 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1 1]


In [52]:
Y_pred = clf.predict(X_test)
acc_log = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_log

54.35

In [53]:
#Recall performed on the Classifier

from sklearn.metrics import recall_score

y_true = Y_train
y_pred = clf.predict(X_test)
recall_score(y_true, y_pred, average=None)

array([0.47826087, 0.62318841])

In [54]:
acc_log = round(recall_score(y_true,y_pred) * 100, 2)
acc_log

62.32

In [55]:
#Applying the KKN Classifier to the data

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train) 
Y_pred = (knn.predict(X_test))
acc_knn = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_knn

56.52

In [56]:
#Recall performed on the Classifier

from sklearn.metrics import recall_score

y_true = Y_train
y_pred = knn.predict(X_test)
recall_score(y_true, y_pred, average=None)

array([0.5942029 , 0.55072464])

In [57]:
acc_log = round(recall_score(y_true,y_pred) * 100, 2)
acc_log

55.07

In [58]:
# An 10 fold cross validation is performed to determine the ideal value for the n-neighbor.

from sklearn.model_selection import cross_val_score

#creating odd list for k for knn
myList = list(range(1,50))

#subsetting just the odd ones
neighbors = filter(lambda x: x % 2 != 0, myList)

#empty list that will hold cv scores
cv_scores = {}

#perform 10-fold cross validation
for k in neighbors:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train, Y_train, cv=10, scoring='accuracy')
    cv_scores[k] = scores.mean()

In [64]:
#The ideal n-neighbor determined

bess_k = max(cv_scores, key=lambda k: cv_scores[k])
bess_k

11

In [65]:
#The KNN Classifier performed with the ideal n-neighbor

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=bess_k)
knn.fit(X_train, Y_train) 
Y_pred = (knn.predict(X_test))
acc_knn = round(accuracy_score(Y_test,Y_pred) * 100, 2)
acc_knn

58.7

In [61]:
#Reacll performed on the classifier

from sklearn.metrics import recall_score

y_true = Y_train
y_pred = knn.predict(X_test)
recall_score(y_true, y_pred, average=None)

array([0.56521739, 0.62318841])

In [62]:
acc_log = round(recall_score(y_true,y_pred) * 100, 2)
acc_log

62.32